name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set npm registry & timeout
      run: |
        yarn config set registry https://registry.yarnpkg.com
        yarn config set network-timeout 600000

    - name: Install `prebuild-install` (dev)
      run: yarn add prebuild-install --dev

    - name: Try to fetch prebuilt native modules
      run: |
        # attempt to download prebuilt binaries for all native deps
        npx prebuild-install || echo "No matching prebuilt binaries"
        # if any native modules are still unbuilt, rebuild via your script
        yarn rebuild-native

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: |
        $env:TSC_COMPILE_ON_ERROR = "true"
        $env:SKIP_PREFLIGHT_CHECK = "true"
        yarn build-prod

    - name: Package for x64
      run: yarn pack:x64

    - name: Ensure bin directory exists
      run: |
        if (!(Test-Path -Path "./bin")) {
          New-Item -ItemType Directory -Force -Path "./bin"
        }

    - name: Move package to bin directory
      run: |
        $outputPath = Get-ChildItem -Path . -Recurse -Filter "*.exe" | Select-Object -ExpandProperty FullName
        Move-Item -Path $outputPath -Destination "./bin"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: electron-app
        path: bin/
