name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Windows Build Tools
      run: |
        npm install -g windows-build-tools
        yarn config set msvs_version 2022

    - name: Set npm registry
      run: |
        yarn config set registry https://registry.yarnpkg.com
        
    - name: Increase Yarn network timeout
      run: |
        yarn config set network-timeout 600000
        
    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: |
        $env:TSC_COMPILE_ON_ERROR = "true"
        $env:SKIP_PREFLIGHT_CHECK = "true"
        yarn build-prod
        
    - name: Package for x64
      run: yarn pack:x64

    - name: Ensure bin directory exists
      run: |
        if (!(Test-Path -Path "./bin")) {
          New-Item -ItemType Directory -Force -Path "./bin"
        }
        
    - name: Move package to bin directory
      run: |
        $outputPath = Get-ChildItem -Path . -Recurse -Filter "*.exe" | Select-Object -ExpandProperty FullName
        Move-Item -Path $outputPath -Destination "./bin"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: electron-app
        path: bin/
